name: Minimal CI/CD Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate-backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Minimal backend build
        working-directory: ./backend
        run: mvn -B compile -DskipTests

  validate-frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Minimal frontend build
        working-directory: ./frontend
        run: npm install && npm run build
